# Generated by Django 5.2.15 on 2026-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='short_description',
            field=models.CharField(default='Sports, Economic, World', max_length=300),
        ),
    ]
