# Generated by Django 5.2.15 on 2026-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_categorydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydata',
            name='button_text',
            field=models.CharField(default='Explore More', max_length=50),
        ),
        migrations.AddField(
            model_name='categorydata',
            name='name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
