# Generated by Django 5.2.15 on 2026-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_herocontent_herocontenttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='image',
            field=models.ImageField(default='hero_image', upload_to='hero_images/'),
        ),
    ]
