# Generated by Django 5.2.15 on 2026-07-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_categorydata_button_text_categorydata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydata',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, related_name='articles_count', to='news_app.category'),
        ),
    ]
