# Generated by Django 5.2.15 on 2026-07-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_categorydata_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydata',
            name='category',
        ),
    ]
